### ISSUE TITLE
Suggestion: Add a way to update lockbot via an API

### ISSUE THREAD

**Issue by greg-cann** [connorads/lockbot#43]
It would be really great if Lockbot had some kind of REST Api, this would allow developers to use their CI/CD tools to trigger locks, and the locks could fail if someone else is using that lock.

**Comment by connorads** [comment]
Thanks for the suggestion @greg-cann (& @bobthemighty)!

My brain is asynchronously having a think about how to implement it in a sensible, maintainable and secure way.

Initial thoughts/notes to self:
- Add a Slack command `/lockbotapi` which generates api key for the current user which has their permissions and performs actions as them _(if users want to add bot/service account they need to register one in their slack workspace and generate an API key for them that way)_
- Create api to perform actions, will need a way to expose data in REST like format instead of Slack Markdown messages, might get my `Lockbot` abstraction to return a message and data so that domain logic is encapsulated

**Comment by connorads** [comment]
Anonymous feedback:
> Nice tool to help with teams working on shared repos! Would have rated higher if there was more integration with CI pipelines.

> E.g., if nobody has locked an environment, then when approving a deploy to that environment, lockbot would send a message that the user who approved the deploy has locked that environment.

> E.g. if somebody has already locked the environment and another person attempts to deploy to there, they would be blocked by lockbot somehow
